version: '3.8'

services:
  edge-functions:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - ./supabase/functions:/app/functions
    command: deno run --watch --allow-net --allow-env --allow-read functions/generate-code/index.ts

  frontend:
    image: node:20
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: npm run dev
    environment:
      - VITE_SUPABASE_URL=${SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}